services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: HK_Housing_Agent_Backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    networks:
      - hk_housing_agent_network
    restart: unless-stopped
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: HK_Housing_Agent_Frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8501:8501"
    environment:
      - BACKEND_BASE_URL=http://backend
      - BACKEND_BASE_PORT=8000
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    networks:
      - hk_housing_agent_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  hk_housing_agent_network:
    driver: bridge